### ISSUE TITLE
Respecting sampling in recorders

### ISSUE THREAD

**Issue by ikonst** [lightstep/lightstep-tracer-python#108]
What is the intended functionality around the `sampled` span context? I've noticed that it's propagated from parent spans and it's serialized into carriers, but I couldn't find code to read it during recording or sending spans to the collector.

**Comment by kayousterhout** [comment]
The Lightstep tracers don't currently support sampling.  We support two ways of sending sampled data to Lightstep: the first is via configuring the Lightstep satellite, and the send is to use OpenTelemetry for instrumentation and sample in the OTel collector.

**Comment by ikonst** [comment]
@kayousterhout There seems to be support in the C++ tracer though: https://github.com/lightstep/lightstep-tracer-cpp/blob/v0.8.0/src/lightstep_span.cpp#L164

**Comment by kayousterhout** [comment]
Ah thanks for bringing that to our attention - historically we have not supported tracing in any of the tracers but that C++ tracer is an exception.  The C++ code makes this appear easy to add so we will look into this.

**Comment by ikonst** [comment]
Also see related issue https://github.com/lightstep/lightstep-tracer-go/issues/261. I actually looked at fixing that one, but wanted to run it by the maintainers first.

**Comment by kayousterhout** [comment]
This is something we're open to merging, depending on the complexity of the fix - so helpful to post a PR!
