### ISSUE TITLE
4.0.0 release

### ISSUE THREAD

**Issue by carlosalberto** [lightstep/lightstep-tracer-python#41]
This issue was created to track and discuss the eventual 4.0.0 release. 

This version will include `Span` propagation through `ScopeManager`, pointing the to 2.0.0rc1 and 3.0.0rc1 versions of `opentracing` and `basictracer`, respectively.

## Current status
* The current effort lives in the `carlos/ot-upgrade-2.0` branch.
* The `lightstep` tracer takes an optional `scope_manager` argument, falling back to a thread-local one (provided by `basictracer`).
* Examples have been ported to handle Python 3.4, and a Changelog draft will be added (@katiabazzi)

## Questions
* Should we do a Release Candidates? For OT it makes perfect sense as many different vendors may want to try the API out in their own codebases, and validate it. For the Lightstep tracer, we may instead decide to keep the effort in a branch for now, and release when the final OT packages are ready. Else, do RC iterations as `opentracing` and `basictracer` do.
* It looks the officially supported Python versions are 2.7 and 3.4. My impression is that we should stick to those ones, and, **whenever** we want to support 3.6 (probably after the 4.0.0 release), do another iteration for it.
* Should we create maybe a `v4.0.0` branch to hold the next release, instead of having the changes in `carlos/ot-upgrade-2.0`?

@katiabazzi @frenchfrywpepper @tedsuo

**Comment by tedsuo** [comment]
An implementation of OpenTracing `v2.0-RC1` can now be found on the `v4.0.0` branch: https://github.com/lightstep/lightstep-tracer-python/tree/v4.0.0

**Comment by tedsuo** [comment]
Now that OpenTracing-python `v2.0` has been released, the The `v4.0` branch of the LightStep python tracer has been updated to reflect the final changes:

https://github.com/lightstep/lightstep-tracer-python/tree/v4.0.0

**Comment by carlosalberto** [comment]
Closing this issue as we already did the 4.0 release (along the OT 2.0 bits).
