### ISSUE TITLE
Span start_time has reduced timing resolution when mapped to Timestamp proto

### ISSUE THREAD

**Issue by michael-booth** [lightstep/lightstep-tracer-python#56]
### Issue:
Our team has started integrating python Lightstep support within aiohttp (asyncio) services.
We noticed when doing cross language traces that the python generated span timelines were skewed compared to other spans emitted in the same trace

Span start times as reported in Lightstep UI are always truncated to the second. This is visible when observing the microseconds stamp in Lightstep UI (see below). Note the trailing `000000`.

<img width="237" alt="screen shot 2018-11-06 at 10 11 16" src="https://user-images.githubusercontent.com/13740260/48057645-6df1fc80-e1ac-11e8-876d-ed3f084d2cc0.png">

Digging into the Lightstep code, I believe is due to the following [code line in http_converter.py](https://github.com/lightstep/lightstep-tracer-python/blob/master/lightstep/http_converter.py#L44)

```python
start_timestamp=Timestamp(seconds=int(span.start_time)),
```

Which casts the `span.start_time` (float) to the second (int) and sets it on the Timestamp object.
Since spans sent via proto are now shifted to the second, the resulting finish time (which appears to be calculated start_time + duration) are marked as finishing earlier than they actually did. 
The result of this was we saw spans emitted by downstream traced services appear later in the trace timeline than the parent calling span in python

![screen shot 2018-11-06 at 10 49 21](https://user-images.githubusercontent.com/13740260/48059649-ab0cbd80-e1b1-11e8-812d-79d08affe3f6.png)

### Potential Solution:
Looking at the google docs on Timestamp, it appears we can supply both the seconds and nanos as a parameter to the object. An [example can be found here](https://pythonhosted.org/gax-google-pubsub-v1/google.protobuf.timestamp_pb2.html):

```python
now = time.time()
seconds = int(now)
nanos = int((now - seconds) * 10**9)
timestamp = Timestamp(seconds=seconds, nanos=nanos)
```

After locally applying the suggested code to the http_converter.py,  traces emitted now appear to have the correct resolution.

![screen shot 2018-11-06 at 10 39 37](https://user-images.githubusercontent.com/13740260/48059168-57e63b00-e1b0-11e8-8dec-760bb10f7820.png)

![screen shot 2018-11-06 at 10 58 33](https://user-images.githubusercontent.com/13740260/48060134-f83d5f00-e1b2-11e8-9804-fd93d9aa935e.png)

### Setup: 
python==3.6.6
opentracing==2.0.0
lightstep==4.0.0
googleapis-common-protos==1.5.3

Can you confirm this is unintentional behaviour and whether our proposed solution would be accepted?

Thanks

**Comment by carlosalberto** [comment]
Hey @michael-booth 

Thanks for the report. Indeed, it looks like we could add the nanos part to have better resolution. Anything against doing this @frenchfrywpepper ?

**Comment by frenchfrywpepper** [comment]
Nope, seems smart.

**Comment by michael-booth** [comment]
Given that this is a fairly small amendment - i'm happy to open a PR for the proposed change if that is of help?

**Comment by carlosalberto** [comment]
@frenchfrywpepper Thanks!

@michael-booth Please do!

**Comment by michael-booth** [comment]
thanks for the speedy replies all 👍 - PR opened.

**Comment by michael-booth** [comment]
HI @carlosalberto - just pulled the new release and run in our test service. Traces have the correct resolution on timestamps now and look good in the Lightstep UI 👍

**Comment by carlosalberto** [comment]
Closing this issue. Thanks!
