### ISSUE TITLE
Add constant for "PropagationSingleKey" header

### ISSUE THREAD

**Issue by airstandley** [lightstep/lightstep-tracer-python#73]
Recently switched over to using the LightstepBinaryPropagator to get a python app playing nice with Envoy which uses Lightstep's C++ tracer with single key propagation on. 

It seemed a bit silly to have to define the header constant ourselves since this library does not appear to define it anywhere. (Apologizes if I just missed it in my search)

Adding a constant similar to https://github.com/lightstep/lightstep-tracer-cpp/blob/master/src/tracer/propagation.cpp#L26 in `propagation.py` would be appreciated.

**Comment by andrewhsu** [comment]
closing old issue. if this is truly desired, reopen with example of how this change can help fix a situation.
