### ISSUE TITLE
Upgrading thrift dependency

### ISSUE THREAD

**Issue by GeorgiosGoniotakis** [lightstep/lightstep-tracer-python#93]
Hello there 😄 Thank you for your contribution to open source. In your [code](https://github.com/lightstep/lightstep-tracer-python/blob/007419fd71f731f02a84aa7c330a8c4694a12b38/setup.py#L11) I observed that you have locked the version of thrift between 0.10 and 0.12. Recently, I scanned one my projects with Snyk and was presented with the following [vulnerability report](https://app.snyk.io/vuln/SNYK-PYTHON-THRIFT-474615). Are there any plans of upgrading thrift to version 13?

**Comment by codeboten** [comment]
Hey @GeorgiosGoniotakis, thanks for raising this issue. The version of thrift was updated in #94 which was released in [4.4.3](https://pypi.org/project/lightstep/4.4.3/).

**Comment by andrewhsu** [comment]
Is this issue now resolved with https://github.com/lightstep/lightstep-tracer-python/releases/tag/4.4.3 ?

**Comment by GeorgiosGoniotakis** [comment]
Yes! Thank you for that.
