### ISSUE TITLE
Research performance testing

### ISSUE THREAD

**Issue by ocelotl** [lightstep/lightstep-tracer-python#97]
We are having random results when it comes to performance testing. Research for a possible solution that enables performance testing to have a reliable testing base that produces repeatable performance testing results.

**Comment by andrewhsu** [comment]
Tracking issue to come back to max throughput tests after disabling it d45a4acbff0c738d7c66efc5e78532d35b2212cb

**Comment by ocelotl** [comment]
Stale issue, closing
